import { BrainCircuit, CheckCircle2, CircleX, Cpu } from "lucide-react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";

import { Section } from "@/components/clinician/Section";
import { StatusBadge } from "@/components/clinician/StatusBadge";
import { PipelineSchema, type PipelineGeneration } from "@/lib/api/clinician";
import { backendGet } from "@/lib/api/server";
import { formatDateTime } from "@/lib/format";

export const metadata: Metadata = { title: "AI pipeline" };

const OBJECTIVE_NAMES: Record<string, string> = {
  word_retrieval: "Word retrieval",
  sentence_formation: "Sentence formation",
  descriptive_language: "Descriptive language",
};

const SOURCE: Record<string, string> = {
  ai: "Generated by the AI",
  rule: "Rule-based (AI output not used)",
  fallback: "Conservative fallback",
};

function Json({ value }: { value: unknown }) {
  return (
    <pre className="max-h-72 overflow-auto rounded-control bg-ink p-4 text-sm leading-relaxed whitespace-pre-wrap text-white">
      {typeof value === "string" ? value : JSON.stringify(value, null, 2)}
    </pre>
  );
}

function Step({
  n,
  title,
  children,
}: {
  n: number;
  title: string;
  children: ReactNode;
}) {
  return (
    <li className="grid gap-3 sm:grid-cols-[2.5rem_1fr]">
      <span
        aria-hidden="true"
        className="grid size-10 place-items-center rounded-full bg-accent-soft font-bold text-accent-hover"
      >
        {n}
      </span>
      <div className="flex min-w-0 flex-col gap-2">
        <h4 className="font-bold">
          <span className="sr-only">Step {n}: </span>
          {title}
        </h4>
        {children}
      </div>
    </li>
  );
}

function Attempts({ gen }: { gen: PipelineGeneration }) {
  return (
    <ul className="flex flex-col gap-2">
      {gen.attempts.map((a) => (
        <li
          key={a.attempt}
          className="flex flex-wrap items-center gap-2 rounded-control border border-line p-3 text-sm"
        >
          {a.status === "accepted" ? (
            <StatusBadge tone="success">Attempt {a.attempt}: valid</StatusBadge>
          ) : (
            <StatusBadge tone="warning">
              Attempt {a.attempt}: {a.status} at {a.failed_stage}
            </StatusBadge>
          )}
          <span className="text-ink-muted">
            {a.provider} · {a.model} · {a.latency_ms} ms
            {a.usage?.output_tokens
              ? ` · ${a.usage.prompt_tokens} prompt + ${a.usage.output_tokens} output tokens`
              : ""}
          </span>
          {a.reason_codes.length > 0 && (
            <span className="w-full font-mono text-ink-muted">
              {a.reason_codes.join(", ")}
            </span>
          )}
        </li>
      ))}
    </ul>
  );
}

function Prompt({ gen }: { gen: PipelineGeneration }) {
  return (
    <details className="rounded-control border border-line p-3">
      <summary className="min-h-target cursor-pointer content-center font-bold">
        Show the full prompt ({gen.prompt_version})
      </summary>
      <div className="mt-3 flex flex-col gap-3">
        <p className="text-sm font-bold text-ink-muted">System message</p>
        <Json value={gen.system_prompt ?? "(older prompt version)"} />
        <p className="text-sm font-bold text-ink-muted">User message</p>
        <Json value={gen.user_prompt ?? "(older prompt version)"} />
      </div>
    </details>
  );
}

export default async function AIPipelinePage({
  params,
}: PageProps<"/clinician/patients/[patientId]/ai-pipeline">) {
  const { patientId } = await params;
  const data = await backendGet(
    `/patients/${patientId}/ai-pipeline`,
    PipelineSchema,
  );
  if (!data) notFound();
  const { status } = data;

  return (
    <div className="flex flex-col gap-10">
      <div className="flex flex-col gap-3">
        <h1 className="text-2xl font-bold">AI pipeline (demonstration view)</h1>
        <p className="text-ink-muted">
          Development-only view of each step for the latest exercises: from
          patient performance to the prompt, the language model&rsquo;s output,
          validation, the deterministic score and the generated feedback.
        </p>
        <p className="flex flex-wrap items-center gap-2">
          <Cpu aria-hidden="true" size={18} className="text-accent" />
          {status.generative ? (
            <StatusBadge tone={status.model_available ? "success" : "warning"}>
              {status.model_available
                ? `Local LLM ready: ${status.model} via Ollama`
                : `Ollama not ready (${status.model})`}
            </StatusBadge>
          ) : (
            <StatusBadge tone="neutral">
              Provider: {status.provider} (not a language model)
            </StatusBadge>
          )}
        </p>
      </div>

      <Section
        id="abilities"
        title="Patient performance: learned ability model"
        description="Online logistic (Rasch/Elo-style) estimate per objective, from scored answers since the latest fresh start. Context for the AI; the difficulty itself comes from the deterministic rule."
      >
        <dl className="grid gap-4 md:grid-cols-3">
          {Object.values(data.abilities).map((a) => (
            <div
              key={a.objective}
              className="flex flex-col gap-1 rounded-card border border-line bg-surface p-5 shadow-card"
            >
              <dt className="flex items-center gap-2 font-bold">
                <BrainCircuit
                  aria-hidden="true"
                  size={18}
                  className="text-accent"
                />
                {OBJECTIVE_NAMES[a.objective] ?? a.objective}
              </dt>
              <dd className="text-sm text-ink-muted">
                {a.attempts} answers · recent accuracy{" "}
                {a.recent_accuracy === null
                  ? "—"
                  : `${Math.round(a.recent_accuracy * 100)}%`}
              </dd>
              <dd className="text-sm text-ink-muted">
                ability θ = {a.ability.toFixed(2)} · trend{" "}
                {a.trend.replaceAll("_", " ")} · {a.status.replaceAll("_", " ")}
              </dd>
            </div>
          ))}
        </dl>
      </Section>

      <Section
        id="traces"
        title="Latest exercises, step by step"
        description="Newest first. Open one to follow it through the pipeline."
      >
        <ol className="flex flex-col gap-4">
          {data.traces.map((t, i) => {
            const next = data.traces[i - 1];
            return (
              <li key={`${t.issued_at}-${t.position}`}>
                <details
                  open={i === 0}
                  className="rounded-card border border-line bg-surface shadow-card"
                >
                  <summary className="flex min-h-target cursor-pointer flex-wrap items-center gap-3 p-5">
                    <span className="font-bold">Picture {t.position}</span>
                    <span>{t.objective_label}</span>
                    <span className="text-ink-muted">
                      {t.exercise_type.replaceAll("_", " ")} · difficulty{" "}
                      {t.difficulty} · {formatDateTime(t.issued_at)}
                    </span>
                    {t.source === "ai" ? (
                      <StatusBadge tone="info">AI-generated</StatusBadge>
                    ) : (
                      <StatusBadge tone="neutral">
                        {SOURCE[t.source]}
                      </StatusBadge>
                    )}
                  </summary>
                  <ol className="flex flex-col gap-6 border-t border-line p-5">
                    <Step n={1} title="Rehabilitation objective">
                      <p>
                        {t.objective_label} →{" "}
                        {t.exercise_type.replaceAll("_", " ")}
                      </p>
                    </Step>
                    <Step n={2} title="Structured patient context">
                      {t.generation ? (
                        <Json value={t.generation.context} />
                      ) : (
                        <p className="text-ink-muted">
                          No AI request for this exercise (AI disabled).
                        </p>
                      )}
                    </Step>
                    {t.generation && (
                      <>
                        <Step n={3} title="Prompt engineering">
                          <p>
                            Prompt version{" "}
                            <code className="font-mono">
                              {t.generation.prompt_version}
                            </code>
                          </p>
                          <Prompt gen={t.generation} />
                        </Step>
                        <Step n={4} title="Generated output and validation">
                          <Attempts gen={t.generation} />
                          {t.generation.attempts.at(-1)?.raw_output && (
                            <Json
                              value={t.generation.attempts.at(-1)!.raw_output}
                            />
                          )}
                        </Step>
                      </>
                    )}
                    <Step n={5} title="Exercise shown to the patient">
                      <div className="flex flex-wrap gap-4">
                        {t.image_url && (
                          // eslint-disable-next-line @next/next/no-img-element
                          <img
                            src={t.image_url}
                            alt={`Picture: ${t.picture ?? ""}`}
                            width={120}
                            height={90}
                            className="h-24 w-auto rounded-control border border-line object-cover"
                          />
                        )}
                        <div className="flex flex-col gap-1">
                          <p className="font-bold">{t.shown.prompt}</p>
                          {t.shown.cues.length > 0 && (
                            <p className="text-ink-muted">
                              Hints: {t.shown.cues.join(" · ")}
                            </p>
                          )}
                          {t.shown.words && (
                            <p className="text-ink-muted">
                              Word bank (from the catalogue):{" "}
                              {t.shown.words.join(", ")}
                            </p>
                          )}
                          <p className="text-sm text-ink-muted">
                            {SOURCE[t.source]}
                          </p>
                        </div>
                      </div>
                    </Step>
                    <Step
                      n={6}
                      title="Patient response and deterministic score"
                    >
                      {t.response ? (
                        <div className="flex flex-col gap-1">
                          <p>
                            &ldquo;{t.response.text ?? "(skipped)"}&rdquo;{" "}
                            <span className="text-ink-muted">
                              ({t.response.mode})
                            </span>
                          </p>
                          <p className="flex flex-wrap items-center gap-2">
                            {t.response.outcome === "correct" ? (
                              <CheckCircle2
                                aria-hidden="true"
                                size={18}
                                className="text-success"
                              />
                            ) : (
                              <CircleX
                                aria-hidden="true"
                                size={18}
                                className="text-ink-muted"
                              />
                            )}
                            Outcome <strong>{t.response.outcome}</strong> ·
                            score {t.response.score} · rule{" "}
                            {t.response.match_type}
                          </p>
                          {t.response.concepts_matched && (
                            <p className="text-ink-muted">
                              Concepts found:{" "}
                              {t.response.concepts_matched.join(", ") || "none"}
                              {" · "}missing:{" "}
                              {t.response.concepts_missing?.join(", ") ||
                                "none"}
                            </p>
                          )}
                        </div>
                      ) : (
                        <p className="text-ink-muted">Not answered yet.</p>
                      )}
                    </Step>
                    <Step n={7} title="AI feedback (after scoring)">
                      {t.feedback ? (
                        <div className="flex flex-col gap-2">
                          {t.feedback.output ? (
                            <p className="rounded-control bg-accent-soft p-3 text-lg">
                              {String(t.feedback.output.feedback)}
                              {t.feedback.output.optional_hint
                                ? ` ${String(t.feedback.output.optional_hint)}`
                                : ""}
                            </p>
                          ) : (
                            <p className="text-ink-muted">
                              No valid feedback: the patient saw the standard
                              message only.
                            </p>
                          )}
                          <Attempts gen={t.feedback} />
                          <Prompt gen={t.feedback} />
                        </div>
                      ) : (
                        <p className="text-ink-muted">
                          No AI feedback requested for this answer.
                        </p>
                      )}
                    </Step>
                    <Step n={8} title="Next personalized exercise">
                      <p className="text-ink-muted">
                        {next
                          ? `Picture ${next.position}: ${next.objective_label}, difficulty ${next.difficulty} (${SOURCE[next.source]}).`
                          : "Not issued yet."}
                      </p>
                    </Step>
                  </ol>
                </details>
              </li>
            );
          })}
        </ol>
      </Section>
    </div>
  );
}
