"""Write .env.production with strong random secrets for compose.prod.yaml.

Usage:  python scripts/generate_prod_env.py [--site-address localhost]
Refuses to overwrite an existing file. The file is git-ignored; keep it out of backups
that leave the host. Standard library only.
"""

import argparse
import base64
import secrets
import sys
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / ".env.production"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--site-address", default="localhost")
    args = p.parse_args()
    if TARGET.exists():
        sys.exit(f"refused: {TARGET.name} already exists")

    def token() -> str:
        return secrets.token_urlsafe(32)

    values = {
        "SITE_ADDRESS": args.site_address,
        "POSTGRES_SUPERUSER_PASSWORD": token(),
        "POSTGRES_MIGRATOR_PASSWORD": token(),
        "POSTGRES_APP_PASSWORD": token(),
        "REDIS_PASSWORD": token(),
        "MINIO_ROOT_USER": "rehabmind-root",
        "MINIO_ROOT_PASSWORD": token(),
        "S3_ACCESS_KEY": "rehabmind-app",
        "S3_SECRET_KEY": token(),
        "AUDIO_ENCRYPTION_KEY": base64.b64encode(secrets.token_bytes(32)).decode(),
    }
    TARGET.write_text(
        "# Generated by scripts/generate_prod_env.py. Never commit.\n"
        + "".join(f"{k}={v}\n" for k, v in values.items()),
        encoding="utf-8",
    )
    print(f"wrote {TARGET.name}")


if __name__ == "__main__":
    main()
