"""audio assets

Revision ID: 647b3b061970
Revises: 2af4571db567
Create Date: 2026-10-05 22:41:42.089588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "647b3b061970"
down_revision: str | Sequence[str] | None = "2af4571db567"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.String(length=80), nullable=True),
        sa.Column("content_type", sa.String(length=60), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.String(length=40), nullable=True),
        sa.Column("response_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_audio_assets_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_audio_assets_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["exercise_responses.id"],
            name=op.f("fk_audio_assets_response_id_exercise_responses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_assets")),
    )
    op.create_index(
        op.f("ix_audio_assets_exercise_id"), "audio_assets", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_audio_assets_patient_id"), "audio_assets", ["patient_id"], unique=False
    )
    op.create_index(
        "uq_audio_assets_one_in_flight",
        "audio_assets",
        ["exercise_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_audio_assets_one_in_flight",
        table_name="audio_assets",
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.drop_index(op.f("ix_audio_assets_patient_id"), table_name="audio_assets")
    op.drop_index(op.f("ix_audio_assets_exercise_id"), table_name="audio_assets")
    op.drop_table("audio_assets")
    # ### end Alembic commands ###
