"""clinical constraints and practice loop

Revision ID: 2af4571db567
Revises: 12216bca02e3
Create Date: 2026-10-05 22:04:38.187706

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2af4571db567"
down_revision: str | Sequence[str] | None = "12216bca02e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENFORCE_CONSTRAINTS_FN = """
CREATE FUNCTION enforce_exercise_constraints() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    cs clinical_constraint_sets%ROWTYPE;
    latest integer;
    session_patient uuid;
BEGIN
    SELECT * INTO cs FROM clinical_constraint_sets WHERE id = NEW.constraint_set_id;
    IF NOT FOUND OR cs.patient_id <> NEW.patient_id THEN
        RAISE EXCEPTION 'constraint set does not belong to patient' USING ERRCODE = '23514';
    END IF;
    SELECT max(version) INTO latest FROM clinical_constraint_sets WHERE patient_id = NEW.patient_id;
    IF cs.version <> latest THEN
        RAISE EXCEPTION 'exercise must use the latest constraint set' USING ERRCODE = '23514';
    END IF;
    SELECT patient_id INTO session_patient FROM practice_sessions WHERE id = NEW.session_id;
    IF session_patient IS DISTINCT FROM NEW.patient_id THEN
        RAISE EXCEPTION 'session does not belong to patient' USING ERRCODE = '23514';
    END IF;
    IF NEW.difficulty < cs.min_difficulty OR NEW.difficulty > cs.max_difficulty THEN
        RAISE EXCEPTION 'difficulty % outside clinician range %-%',
            NEW.difficulty, cs.min_difficulty, cs.max_difficulty USING ERRCODE = '23514';
    END IF;
    IF NOT (NEW.exercise_type = ANY (cs.allowed_exercise_types)) THEN
        RAISE EXCEPTION 'exercise type % not allowed', NEW.exercise_type USING ERRCODE = '23514';
    END IF;
    IF NOT (NEW.response_modes <@ cs.allowed_response_modes) THEN
        RAISE EXCEPTION 'response mode not allowed' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stimuli",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=64), nullable=False),
        sa.Column("accepted_answers", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("image_path", sa.String(length=200), nullable=False),
        sa.Column("license", sa.String(length=40), nullable=False),
        sa.Column("catalog_version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stimuli")),
        sa.UniqueConstraint("slug", name=op.f("uq_stimuli_slug")),
    )
    op.create_index(op.f("ix_stimuli_category"), "stimuli", ["category"], unique=False)
    op.create_index(op.f("ix_stimuli_difficulty"), "stimuli", ["difficulty"], unique=False)
    op.create_table(
        "clinical_constraint_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("allowed_exercise_types", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("allowed_response_modes", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("allowed_categories", postgresql.ARRAY(sa.String(length=40)), nullable=True),
        sa.Column("min_difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("max_difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("max_exercises_per_session", sa.SmallInteger(), nullable=False),
        sa.Column("advance_after_correct", sa.SmallInteger(), nullable=False),
        sa.Column("step_back_after_incorrect", sa.SmallInteger(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "advance_after_correct BETWEEN 1 AND 10",
            name=op.f("ck_clinical_constraint_sets_advance_rule"),
        ),
        sa.CheckConstraint(
            "cardinality(allowed_exercise_types) > 0",
            name=op.f("ck_clinical_constraint_sets_has_types"),
        ),
        sa.CheckConstraint(
            "cardinality(allowed_response_modes) > 0",
            name=op.f("ck_clinical_constraint_sets_has_modes"),
        ),
        sa.CheckConstraint(
            "max_exercises_per_session BETWEEN 1 AND 50",
            name=op.f("ck_clinical_constraint_sets_session_limit"),
        ),
        sa.CheckConstraint(
            "min_difficulty >= 1 AND max_difficulty <= 5 AND min_difficulty <= max_difficulty",
            name=op.f("ck_clinical_constraint_sets_difficulty_range"),
        ),
        sa.CheckConstraint(
            "step_back_after_incorrect BETWEEN 1 AND 10",
            name=op.f("ck_clinical_constraint_sets_step_back_rule"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_clinical_constraint_sets_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_clinical_constraint_sets_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinical_constraint_sets")),
        sa.UniqueConstraint(
            "patient_id", "version", name=op.f("uq_clinical_constraint_sets_patient_id")
        ),
    )
    op.create_index(
        op.f("ix_clinical_constraint_sets_patient_id"),
        "clinical_constraint_sets",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "performance_profiles",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_type", sa.String(length=40), nullable=False),
        sa.Column("target_difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("consecutive_correct", sa.SmallInteger(), nullable=False),
        sa.Column("consecutive_incorrect", sa.SmallInteger(), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("total_correct", sa.Integer(), nullable=False),
        sa.Column("recent_outcomes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_performance_profiles_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "patient_id", "exercise_type", name=op.f("pk_performance_profiles")
        ),
    )
    op.create_table(
        "practice_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("planned_exercises", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_practice_sessions_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_sessions")),
    )
    op.create_index(
        op.f("ix_practice_sessions_patient_id"), "practice_sessions", ["patient_id"], unique=False
    )
    op.create_index(
        "uq_practice_sessions_one_active",
        "practice_sessions",
        ["patient_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("constraint_set_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("exercise_type", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("response_modes", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("stimulus_id", sa.Uuid(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("generator_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["constraint_set_id"],
            ["clinical_constraint_sets.id"],
            name=op.f("fk_exercises_constraint_set_id_clinical_constraint_sets"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_exercises_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice_sessions.id"],
            name=op.f("fk_exercises_session_id_practice_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stimulus_id"], ["stimuli.id"], name=op.f("fk_exercises_stimulus_id_stimuli")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
        sa.UniqueConstraint("session_id", "position", name=op.f("uq_exercises_session_id")),
    )
    op.create_index(op.f("ix_exercises_patient_id"), "exercises", ["patient_id"], unique=False)
    op.create_index(op.f("ix_exercises_session_id"), "exercises", ["session_id"], unique=False)
    op.create_table(
        "exercise_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_responses_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_exercise_responses_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_responses")),
        sa.UniqueConstraint("exercise_id", name=op.f("uq_exercise_responses_exercise_id")),
    )
    op.create_index(
        op.f("ix_exercise_responses_patient_id"), "exercise_responses", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###

    # ---- Clinical safety: defence in depth, independent of application code ----
    op.execute(ENFORCE_CONSTRAINTS_FN)
    op.execute(
        "CREATE TRIGGER exercises_enforce_constraints BEFORE INSERT OR UPDATE OF "
        "difficulty, exercise_type, constraint_set_id, patient_id, session_id, response_modes "
        "ON exercises FOR EACH ROW EXECUTE FUNCTION enforce_exercise_constraints()"
    )
    # Constraint sets are immutable versions; the runtime role may only add new ones.
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON clinical_constraint_sets FROM sra_app")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS exercises_enforce_constraints ON exercises")
    op.execute("DROP FUNCTION IF EXISTS enforce_exercise_constraints()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercise_responses_patient_id"), table_name="exercise_responses")
    op.drop_table("exercise_responses")
    op.drop_index(op.f("ix_exercises_session_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_patient_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(
        "uq_practice_sessions_one_active",
        table_name="practice_sessions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_practice_sessions_patient_id"), table_name="practice_sessions")
    op.drop_table("practice_sessions")
    op.drop_table("performance_profiles")
    op.drop_index(
        op.f("ix_clinical_constraint_sets_patient_id"), table_name="clinical_constraint_sets"
    )
    op.drop_table("clinical_constraint_sets")
    op.drop_index(op.f("ix_stimuli_difficulty"), table_name="stimuli")
    op.drop_index(op.f("ix_stimuli_category"), table_name="stimuli")
    op.drop_table("stimuli")
    # ### end Alembic commands ###
