"""ai generation exercise position

Revision ID: a6969e4a1fd7
Revises: e19f77e26305
Create Date: 2026-10-05 23:40:52.550115

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6969e4a1fd7"
down_revision: str | Sequence[str] | None = "e19f77e26305"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_generations", sa.Column("exercise_position", sa.SmallInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_generations", "exercise_position")
    # ### end Alembic commands ###
