"""photo stimuli

Revision ID: 103dc834422a
Revises: c7cdeb536db4
Create Date: 2026-10-06 14:12:27.729519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "103dc834422a"
down_revision: str | Sequence[str] | None = "c7cdeb536db4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stimuli", sa.Column("kind", sa.String(length=10), server_default="icon", nullable=False)
    )
    op.add_column(
        "stimuli",
        sa.Column(
            "exercise_types",
            postgresql.ARRAY(sa.String(length=40)),
            server_default="{picture_naming}",
            nullable=False,
        ),
    )
    op.add_column(
        "stimuli",
        sa.Column(
            "task", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column("stimuli", sa.Column("attribution", sa.String(length=200), nullable=True))
    op.add_column("stimuli", sa.Column("source_url", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stimuli", "source_url")
    op.drop_column("stimuli", "attribution")
    op.drop_column("stimuli", "task")
    op.drop_column("stimuli", "exercise_types")
    op.drop_column("stimuli", "kind")
    # ### end Alembic commands ###
