"""indexes for clinician queries

Revision ID: c7cdeb536db4
Revises: a6969e4a1fd7
Create Date: 2026-10-06 00:28:50.306837

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7cdeb536db4"
down_revision: str | Sequence[str] | None = "a6969e4a1fd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_ai_generations_patient_created",
        "ai_generations",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_exercise_responses_patient_created",
        "exercise_responses",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_practice_sessions_patient_started",
        "practice_sessions",
        ["patient_id", "started_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_practice_sessions_patient_started", table_name="practice_sessions")
    op.drop_index("ix_exercise_responses_patient_created", table_name="exercise_responses")
    op.drop_index("ix_ai_generations_patient_created", table_name="ai_generations")
    # ### end Alembic commands ###
