"""ai generations and hints

Revision ID: e19f77e26305
Revises: 647b3b061970
Create Date: 2026-10-05 23:07:11.963963

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e19f77e26305"
down_revision: str | Sequence[str] | None = "647b3b061970"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_generations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=True),
        sa.Column("task", sa.String(length=60), nullable=False),
        sa.Column("attempt", sa.SmallInteger(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=40), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("constraint_set_id", sa.Uuid(), nullable=False),
        sa.Column("constraint_version", sa.Integer(), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("parsed_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failed_stage", sa.String(length=16), nullable=True),
        sa.Column("reason_codes", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constraint_set_id"],
            ["clinical_constraint_sets.id"],
            name=op.f("fk_ai_generations_constraint_set_id_clinical_constraint_sets"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["exercises.id"], name=op.f("fk_ai_generations_exercise_id_exercises")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_ai_generations_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice_sessions.id"],
            name=op.f("fk_ai_generations_session_id_practice_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_generations")),
    )
    op.create_index(
        op.f("ix_ai_generations_created_at"), "ai_generations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ai_generations_patient_id"), "ai_generations", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_generations_session_id"), "ai_generations", ["session_id"], unique=False
    )
    op.add_column(
        "audio_assets", sa.Column("hints_used", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###
    # AI audit trail is append-only for the runtime role.
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON ai_generations FROM rehabmind_app")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audio_assets", "hints_used")
    op.drop_index(op.f("ix_ai_generations_session_id"), table_name="ai_generations")
    op.drop_index(op.f("ix_ai_generations_patient_id"), table_name="ai_generations")
    op.drop_index(op.f("ix_ai_generations_created_at"), table_name="ai_generations")
    op.drop_table("ai_generations")
    # ### end Alembic commands ###
